name: utility
description: This package contains utility classes used in our Dart projects.
version: 1.0.6
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.9
